/* =========================================================
   UAF CAMPAIGN DRIVE — ADMIN CORE & EXPORT ENGINE (v31)
   =========================================================
   Covers:
   - Admin authentication & session recovery
   - Operations dashboard with 4 KPI cards & live stories summary
   - One-Click Data Download engine (CSV with UTF-8 BOM for Excel)
   - Single record receipt / review copy exporter
   - 4-area module switching (Dashboard, Stories, Donations, Submissions)
   ========================================================= */

(() => {
  "use strict";

  const API_URL = (window.UAF_CONFIG && window.UAF_CONFIG.API_URL) || "";

  const loginScreen = document.getElementById("login-screen");
  const dashboardScreen = document.getElementById("dashboard-screen");
  const loginForm = document.getElementById("login-form");
  const loginError = document.getElementById("login-error");
  const logoutBtn = document.getElementById("logout-btn");

  async function callApi(action, payload = {}) {
    const res = await fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "text/plain;charset=utf-8" },
      body: JSON.stringify(Object.assign({ action }, payload))
    });
    return res.json();
  }
  window.__uafAdminCallApi = callApi;

  function escapeHtml(str) {
    const div = document.createElement("div");
    div.textContent = str == null ? "" : String(str);
    return div.innerHTML;
  }
  window.__uafEscapeHtml = escapeHtml;

  function formatMoney(num) {
    const n = Number(num) || 0;
    return "$" + n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
  window.__uafFormatMoney = formatMoney;

  /* ---------------------------------------------------------
     ONE-CLICK DATA DOWNLOAD ENGINE (Excel-compatible UTF-8 BOM)
  --------------------------------------------------------- */
  function downloadCsv(filename, headers, rows) {
    const csvLines = [];
    
    // Header line
    csvLines.push(headers.map(escapeCsvField).join(","));

    // Data rows
    rows.forEach((row) => {
      csvLines.push(headers.map((h) => escapeCsvField(row[h] != null ? row[h] : "")).join(","));
    });

    // Prepend UTF-8 BOM (\uFEFF) so Excel opens without encoding issues
    const csvContent = "\uFEFF" + csvLines.join("\r\n");
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", filename.endsWith(".csv") ? filename : filename + ".csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
  window.__uafDownloadCsv = downloadCsv;

  function escapeCsvField(val) {
    let str = String(val == null ? "" : val);
    if (str.includes('"') || str.includes(',') || str.includes('\n') || str.includes('\r')) {
      str = '"' + str.replace(/"/g, '""') + '"';
    }
    return str;
  }

  function downloadRecordReceipt(filename, title, recordObj) {
    const lines = [
      "===========================================================",
      "  UPSKILL AFRICA FOUNDATION (UAF) — OFFICIAL RECORD RECEIPT",
      "===========================================================",
      `Title: ${title}`,
      `Generated At: ${new Date().toISOString()}`,
      `Generated By: ${window.__uafAdminSession?.name || "Admin"}`,
      "-----------------------------------------------------------"
    ];

    Object.keys(recordObj).forEach((key) => {
      lines.push(`${key}: ${recordObj[key] != null ? recordObj[key] : ""}`);
    });

    lines.push("===========================================================");
    lines.push("© 2026 Upskill Africa Foundation. All Rights Reserved.");

    const content = "\uFEFF" + lines.join("\r\n");
    const blob = new Blob([content], { type: "text/plain;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", filename.endsWith(".txt") ? filename : filename + ".txt");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
  window.__uafDownloadRecordReceipt = downloadRecordReceipt;

  /* ---------------------------------------------------------
     ONE-CLICK DOWNLOAD ALL DATA
  --------------------------------------------------------- */
  async function downloadAllData() {
    const session = window.__uafAdminSession;
    if (!session || !session.token) {
      alert("Please log in to download data.");
      return;
    }

    const btn = document.getElementById("btn-dash-download-all");
    if (btn) {
      btn.setAttribute("disabled", "true");
      btn.textContent = "Generating Export Files...";
    }

    try {
      // 1. Stories
      const storiesRes = await callApi("listStories", { token: session.token });
      if (storiesRes.ok && Array.isArray(storiesRes.stories)) {
        downloadCsv(`UAF_Campaign_Stories_${new Date().toISOString().slice(0, 10)}.csv`, 
          ["storyId", "title", "goal", "raised", "percent", "status", "county", "community", "summary", "createdAt"],
          storiesRes.stories
        );
      }

      // 2. Donations
      const donationsRes = await callApi("listDonations", { token: session.token, status: "ALL" });
      if (donationsRes.ok && Array.isArray(donationsRes.donations)) {
        downloadCsv(`UAF_Donations_All_${new Date().toISOString().slice(0, 10)}.csv`,
          ["transactionId", "storyId", "name", "phone", "email", "amount", "currency", "paymentReference", "verificationStatus", "notes", "createdAt", "verifiedAt", "verifiedBy"],
          donationsRes.donations
        );
      }

      // 3. Evidence Requests
      const evRes = await callApi("listEvidenceRequests", { token: session.token, status: "ALL" });
      if (evRes.ok && Array.isArray(evRes.requests)) {
        downloadCsv(`UAF_Evidence_Requests_${new Date().toISOString().slice(0, 10)}.csv`,
          ["requestId", "requesterName", "email", "organization", "requestDetails", "status", "reviewerNotes", "createdAt", "closedAt"],
          evRes.requests
        );
      }

      // 4. OSSC Submissions
      const osscRes = await callApi("listOutOfSchoolSubmissions", { token: session.token, status: "ALL" });
      if (osscRes.ok && Array.isArray(osscRes.submissions)) {
        downloadCsv(`UAF_OSSC_Submissions_${new Date().toISOString().slice(0, 10)}.csv`,
          ["submissionId", "reporterName", "reporterPhone", "county", "community", "childCount", "notes", "status", "reviewedBy", "reviewedAt", "reviewerNotes", "timestamp"],
          osscRes.submissions
        );
      }

      alert("All datasets exported successfully as Excel-compatible CSV files.");
    } catch (err) {
      alert("Export notice: Could not download all tables. Check connection and retry.");
    } finally {
      if (btn) {
        btn.removeAttribute("disabled");
        btn.innerHTML = `
          <svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2.2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
          <span>Download All Data (1-Click)</span>
        `;
      }
    }
  }

  document.getElementById("btn-dash-download-all")?.addEventListener("click", downloadAllData);

  /* ---------------------------------------------------------
     DASHBOARD SUMMARY MODULE
  --------------------------------------------------------- */
  async function loadDashboardSummary() {
    const session = window.__uafAdminSession;
    if (!session || !session.token) return;

    try {
      const res = await callApi("getAdminDashboardSummary", { token: session.token });
      if (res.ok && res.summary) {
        const s = res.summary;
        document.getElementById("kpi-pending-donations").textContent = s.pendingDonationsCount || 0;
        document.getElementById("kpi-verified-funds").textContent = formatMoney(s.totalVerifiedUSD || 0);
        document.getElementById("kpi-verified-count").textContent = `${s.verifiedDonationCount || 0} donation(s) verified`;
        document.getElementById("kpi-new-data-reqs").textContent = s.newDataRequestsCount || 0;
        document.getElementById("kpi-new-ossc-reports").textContent = s.newOsscCount || 0;

        const tableBody = document.getElementById("dash-stories-table-body");
        if (tableBody && Array.isArray(s.storiesSummary)) {
          if (s.storiesSummary.length === 0) {
            tableBody.innerHTML = `<tr><td colspan="6" style="text-align:center;padding:18px;color:var(--ink-400);">No stories published yet.</td></tr>`;
          } else {
            tableBody.innerHTML = s.storiesSummary.map((st) => `
              <tr>
                <td><strong>${escapeHtml(st.title)}</strong><br /><small style="color:var(--ink-400);">${escapeHtml(st.storyId)}</small></td>
                <td>${formatMoney(st.goal)}</td>
                <td style="color:#0284c7;font-weight:700;">${formatMoney(st.raised)}</td>
                <td>
                  <div style="font-size:12px;font-weight:700;margin-bottom:3px;">${st.percent}%</div>
                  <div style="background:#e2e8f0;height:6px;width:100px;border-radius:999px;overflow:hidden;">
                    <div style="background:#0284c7;height:100%;width:${st.percent}%;"></div>
                  </div>
                </td>
                <td><span class="status-badge status-badge--${st.status.toLowerCase()}">${escapeHtml(st.status)}</span></td>
                <td>
                  <button type="button" class="btn btn--outline btn-sm" onclick="window.__uafActivateModule('stories')">Manage</button>
                </td>
              </tr>
            `).join("");
          }
        }
      }
    } catch (err) {
      console.warn("Notice loading dashboard summary:", err);
    }
  }

  document.getElementById("btn-refresh-dashboard")?.addEventListener("click", loadDashboardSummary);

  // KPI card click shortcuts
  document.querySelectorAll(".admin-kpi-card[data-goto-module]").forEach((card) => {
    card.addEventListener("click", () => activateModule(card.dataset.gotoModule));
  });

  /* ---------------------------------------------------------
     AUTHENTICATION & SESSION
  --------------------------------------------------------- */
  function showLogin(msg) {
    dashboardScreen.classList.add("is-hidden");
    loginScreen.classList.remove("is-hidden");
    if (msg) {
      loginError.textContent = msg;
      loginError.classList.remove("is-hidden");
    }
  }

  function showDashboard(session) {
    window.__uafAdminSession = session;
    document.getElementById("welcome-name").textContent = session.name;
    document.getElementById("welcome-role").textContent = session.role === "ADMIN" ? "Administrator" : "Viewer";
    document.getElementById("admin-user-label").textContent = `${session.name} · ${session.role}`;
    loginScreen.classList.add("is-hidden");
    dashboardScreen.classList.remove("is-hidden");
    loadDashboardSummary();
  }

  async function restoreSession() {
    const token = sessionStorage.getItem("uaf_admin_token");
    const name = sessionStorage.getItem("uaf_admin_name");
    const role = sessionStorage.getItem("uaf_admin_role");
    if (!token) return showLogin();

    try {
      const res = await callApi("adminWhoAmI", { token });
      if (res.ok) {
        showDashboard({ token, name: res.name || name || "Admin", role: res.role || role || "ADMIN" });
      } else {
        sessionStorage.clear();
        showLogin();
      }
    } catch (_) {
      showDashboard({ token, name: name || "Admin", role: role || "ADMIN" });
    }
  }

  loginForm.addEventListener("submit", async (e) => {
    e.preventDefault();
    loginError.classList.add("is-hidden");
    const email = document.getElementById("login-email").value.trim();
    const password = document.getElementById("login-password").value;
    const role = document.getElementById("login-role").value;
    const submitBtn = loginForm.querySelector("button[type='submit']");

    submitBtn.setAttribute("disabled", "true");
    submitBtn.textContent = "Authenticating...";

    try {
      const res = await callApi("adminLogin", { email, password });
      if (res.ok && res.token) {
        sessionStorage.setItem("uaf_admin_token", res.token);
        sessionStorage.setItem("uaf_admin_name", res.name || "Administrator");
        sessionStorage.setItem("uaf_admin_role", role);
        showDashboard({ token: res.token, name: res.name || "Administrator", role });
      } else {
        loginError.textContent = res.error || "Invalid email or password.";
        loginError.classList.remove("is-hidden");
      }
    } catch (_) {
      loginError.textContent = "Could not connect to authentication server. Check connection.";
      loginError.classList.remove("is-hidden");
    } finally {
      submitBtn.removeAttribute("disabled");
      submitBtn.textContent = "Sign In";
    }
  });

  logoutBtn.addEventListener("click", () => {
    const token = sessionStorage.getItem("uaf_admin_token");
    if (token) callApi("adminLogout", { token }).catch(() => {});
    sessionStorage.clear();
    window.__uafAdminSession = null;
    showLogin();
  });

  /* ---------------------------------------------------------
     4-AREA MODULE REGISTRY & SWITCHER
  --------------------------------------------------------- */
  const moduleRegistry = {};
  window.__uafRegisterAdminModule = function (key, renderFn) {
    moduleRegistry[key] = renderFn;
  };

  function activateModule(key) {
    document.querySelectorAll(".admin-nav__item").forEach((item) => {
      item.classList.toggle("is-active", item.dataset.module === key);
    });

    const dashboardPanel = document.getElementById("admin-modules");
    const modulePanel = document.getElementById("admin-module-panel");
    if (!dashboardPanel || !modulePanel) return;

    if (key === "dashboard") {
      dashboardPanel.classList.remove("is-hidden");
      modulePanel.classList.add("is-hidden");
      loadDashboardSummary();
      return;
    }

    dashboardPanel.classList.add("is-hidden");
    modulePanel.classList.remove("is-hidden");

    const renderFn = moduleRegistry[key];
    if (renderFn) {
      modulePanel.innerHTML = "";
      renderFn(modulePanel, window.__uafAdminSession);
    } else {
      modulePanel.innerHTML = `<div class="admin-card"><p class="admin-muted">Module '${escapeHtml(key)}' is not loaded.</p></div>`;
    }
  }
  window.__uafActivateModule = activateModule;

  document.querySelectorAll(".admin-nav__item[data-module]").forEach((item) => {
    item.addEventListener("click", () => activateModule(item.dataset.module));
  });

  restoreSession();
})();
